**什么是numpy？**

numpy是python中基于数组对象的科学计算库。
提炼关键字，可以得出numpy以下三大特点：
拥有n维数组对象;
拥有广播功能（后面讲到）；
拥有各种科学计算API，任你调用；

**如何安装numpy？**

因为numpy是一个python库，所以使用python包管理工具pip或者conda都可以安装。
安装python后，打开cmd命令行，输入：

In [ ]:
#pip install numpy

**什么是n维数组对象？**

n维数组（ndarray）对象，是一系列同类数据的集合，可以进行索引、切片、迭代操作。
numpy中可以使用array函数创建数组:

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

**如何区分一维、二维、多维？**

判断一个数组是几维，主要是看它有几个轴（axis）。

一个轴表示一维数组，两个轴表示二维数组，以此类推。

每个轴都代表一个一维数组。

比如说，二维数组第一个轴里的每个元素都是一个一维数组，也就是第二个轴。

一维数组一个轴：

In [2]:
[1,2,3]

[1, 2, 3]

二维数组两个轴：

In [3]:
[[0, 1, 2],
 [3, 4, 5]]

[[0, 1, 2], [3, 4, 5]]

三维数组三个轴：

In [4]:
[[[ 0,  1,  2],
  [ 3,  4,  5]],

 [[ 6,  7,  8],
  [ 9, 10, 11]]]

[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]

以此类推n维数组。

**以下表达式运行的结果分别是什么?**

(提示: NaN = not a number, inf = infinity)

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1


In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


**将numpy的datetime64对象转换为datetime的datetime对象。**

- `dt64 = np.datetime64('2020-02-25 22:10:10')`

【知识点：时间日期和时间增量】
- 如何将numpy的datetime64对象转换为datetime的datetime对象？

In [7]:
import numpy as np
import datetime

dt64 = np.datetime64('2020-02-25 22:10:10')
dt = dt64.astype(datetime.datetime)
print(dt, type(dt))
# 2020-02-25 22:10:10 <class 'datetime.datetime'>

2020-02-25 22:10:10 <class 'datetime.datetime'>


**给定一系列不连续的日期序列。填充缺失的日期，使其成为连续的日期序列。**

- `dates = np.arange('2020-02-01', '2020-02-10', 2, np.datetime64)`

【知识点：时间日期和时间增量、数学函数】
- 如何填写不规则系列的numpy日期中的缺失日期？

In [8]:
import numpy as np

dates = np.arange('2020-02-01', '2020-02-10', 2, np.datetime64)
print(dates)
# ['2020-02-01' '2020-02-03' '2020-02-05' '2020-02-07' '2020-02-09']

out = []
for date, d in zip(dates, np.diff(dates)):
    out.extend(np.arange(date, date + d))
fillin = np.array(out)
output = np.hstack([fillin, dates[-1]])
print(output)
# ['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
#  '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09']

['2020-02-01' '2020-02-03' '2020-02-05' '2020-02-07' '2020-02-09']
['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
 '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09']


**如何得到昨天，今天，明天的的日期**

【知识点：时间日期】
- (提示: np.datetime64, np.timedelta64)

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [10]:
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2020-10-20
Today is 2020-10-21
Tomorrow is 2020-10-22



**创建从0到9的一维数字数组。**

【知识点：数组的创建】
- 如何创建一维数组？


In [11]:
#【答案】

import numpy as np

arr = np.arange(10)
print(arr)
# [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


**创建一个元素全为`True`的 3×3 数组。**

【知识点：数组的创建】
- 如何创建一个布尔数组？

In [12]:
#答案
import numpy as np

arr = np.full([3, 3], True, dtype=np.bool)
print(arr)
# [[ True  True  True]
#  [ True  True  True]
#  [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**创建一个长度为10并且除了第五个值为1的空向量**

【知识点：数组的创建】

- (提示: array[4])

In [13]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**创建一个值域范围从10到49的向量**

【知识点：创建数组】

- (提示: np.arange)

In [14]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**创建一个 3x3x3的随机数组**

【知识点：创建数组】

(提示: np.random.random)

In [15]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.86320776 0.37326647 0.12376238]
  [0.86571807 0.6167063  0.79835877]
  [0.30218985 0.09029931 0.69406233]]

 [[0.95412353 0.057905   0.32944806]
  [0.10815566 0.72185839 0.16908564]
  [0.80251711 0.52160004 0.23230243]]

 [[0.43055799 0.61193053 0.53816074]
  [0.88572255 0.475085   0.61029879]
  [0.20404241 0.37039593 0.26970935]]]


**创建一个二维数组，其中边界值为1，其余值为0**

【知识点：二维数组的创建】

- (提示: array[1:-1, 1:-1])

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**创建长度为10的numpy数组，从5开始，在连续的数字之间的步长为3。**

【知识点：数组的创建与属性】
- 如何在给定起始点、长度和步骤的情况下创建一个numpy数组序列？

In [17]:
import numpy as np

start = 5
step = 3
length = 10
a = np.arange(start, start + step * length, step)
print(a)  # [ 5  8 11 14 17 20 23 26 29 32]

[ 5  8 11 14 17 20 23 26 29 32]


**将本地图像导入并将其转换为numpy数组。**

【知识点：数组的创建与属性】
- 如何将图像转换为numpy数组？

In [18]:
import numpy as np
from PIL import Image

img1 = Image.open('test.jpg')
a = np.array(img1)

print(a.shape, a.dtype)
# (959, 959, 3) uint8

(959, 959, 3) uint8
